language: c

branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: false
      language: c
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: ['MATRIX_EVAL="CC=gcc-7 && CF=-DBUILD_SHARED_LIBS=OFF"']
    - os: linux
      sudo: false
      language: c
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: ['MATRIX_EVAL="CC=gcc-7 && CF=-DBUILD_SHARED_LIBS=ON"']
    - os: linux
      sudo: false
      language: c
      env: ['MATRIX_EVAL="CC=clang && CF=-DBUILD_SHARED_LIBS=ON"']
    - os: osx
      sudo: false
      language: c
      env:
        - MATRIX_EVAL="CC=clang" CF=-DBUILD_SHARED_LIBS=ON
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . "$CF"
  - cpack
