version: '{build}'
branches:
  only:
    - master
image:
  - Visual Studio 2017
platform:
  - Win32
  - x64
build_script:
  - cmd: mkdir build && cd build && cmake --version &&  cmake .. -G "Visual Studio 15 2017 %PLATFORM%" && cmake --build . -- /P:Configuration=Release
